runtime: python39

handlers:
# Route the root URL (/) to index.html
- url: /
  static_files: index.html
  upload: index.html

# Route all other URLs to their corresponding files (e.g., /about.html, /style.css)
- url: /(.*)
  static_files: \1
  upload: (.*)